version: "3.8"

networks:
  networks_public:
    external: true
  network_databases:
    external: true

volumes:
  redis:

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
  redis_host_password:
    file: ./secrets/redis_host_password.txt
  postgres_db:
    file: ./secrets/postgres_db.txt

services:
  postgres:
    image: arm64v8/postgres:14-alpine
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=false"
    hostname: postgres
    env_file:
      - .env_postgres
    volumes:
      - /media/disk2/postgres:/var/lib/postgresql/data:rw
    networks:
      - network_databases
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db

  redis:
    image: redis:7.0.10-alpine
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=false"
    hostname: redis
    command:  [
    "sh", "-c",
    '
    docker-entrypoint.sh
    --requirepass "$$(cat $$REDIS_PASSWORD_FILE)"
    '
    ]
    env_file:
      - .env_redis
    volumes:
      - redis:/data
    networks:
      - network_databases
    secrets:
      - redis_host_password
