---
version: '3.8'

networks:
  network_public:
    external: true

services:
  it-tools:
    image: corentinth/it-tools:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_public"
        - "traefik.http.routers.it-tools.tls=true"
        - "traefik.http.routers.it-tools.rule=Host(`veeru.duckdns.org`) && PathPrefix(`/it-tools`)"
        - "traefik.http.services.it-tools.loadbalancer.server.port=80"
    hostname: it-tools
    env_file:
      - .env_it-tools
    networks:
      - network_public
