# Author: Veerendra K
# Description: An Ansible playbook to make awesome Raspberry Pi homeserver

- name: Raspberry Pi Homeserver
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Run update
      apt:
        upgrade: true
        update_cache: yes
      ignore_errors: yes
      become: yes

  post_tasks:
    - name: Run autoremove
      apt:
        autoremove: yes
      become: yes

  tasks:
    - name: Prepare Pi
      import_tasks: tasks/prepare-pi.yml

    - name: Deploy services
      import_tasks: tasks/deploy-services.yml

    - name: Setup firewall rules
      import_tasks: tasks/ufw.yml

    - name: Performing smoke tests
      import_tasks: tasks/smoke-tests.yml
      tags: never
