---
- name: Homeserver Automation
  hosts: all
  vars_files:
    - vars.yml

  roles:
    - veerendra2.prepare_dev_setup

  tasks:
    - name: Prepare Pi
      ansible.builtin.import_tasks: tasks/prepare-pi.yml
      become: true
      tags: prepare-pi

    - name: Deploy services
      ansible.builtin.import_tasks: tasks/deploy-services.yml
      become: true
      tags: services

    - name: Setup firewall rules
      ansible.builtin.import_tasks: tasks/ufw.yml
      become: true

    - name: Performing smoke tests
      ansible.builtin.import_tasks: tasks/smoke-tests.yml
      tags: never
