---
- name: Homeserver Automation
  hosts: localhost
  vars_files:
    - vars.yml

  roles:
    - role: veerendra2.prepare_dev_setup
      tags: system

  tasks:
    - name: Prepare Pi
      ansible.builtin.import_tasks: tasks/prepare-pi.yml
      become: true
      tags: pi

    - name: Deploy services
      ansible.builtin.import_tasks: tasks/deploy-services.yml
      become: true
      tags: services

    - name: Setup firewall rules
      ansible.builtin.import_tasks: tasks/ufw.yml
      become: true

    - name: Run smoke tests
      ansible.builtin.import_tasks: tasks/smoke-tests.yml
      tags: never
