# Author: Veerendra Kakumanu
# Description: An Ansible playbook to make simple Raspberry Pi homeserver

- name: Raspberry Pi Homeserver
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars.yml
    - secrets.yml

  pre_tasks:
    - name: Run Update
      apt:
        upgrade: true
        update_cache: yes
      ignore_errors: yes
      become: yes

  post_tasks:
    - name: Run autoremove
      apt:
        autoremove: yes
      become: yes

  handlers:
    - name: Include handlers
      import_tasks: tasks/handlers.yml

  tasks:
    - name: Install Packages
      import_tasks: tasks/install-pkgs.yml

    - name: Setup monitoring
      import_tasks: tasks/monitoring.yml

    - name: Setup pihole
      import_tasks: tasks/pihole.yml

    - name: Setup portainer
      import_tasks: tasks/portainer.yml

    - name: Setup homer
      import_tasks: tasks/homer.yml

    - name: Setup jellyfin
      import_tasks: tasks/jellyfin.yml

    - name: Setup nextcloud
      import_tasks: tasks/nextcloud.yml

    - name: Setup filebrowser
      import_tasks: tasks/filebrowser.yml

    - name: Setup nginx
      import_tasks: tasks/nginx.yml
