# Author: Veerendra Kakumanu
# Description: An Ansible playbook to make awesome Raspberry Pi homeserver(Legacy Setup)

- name: Raspberry Pi Homeserver
  hosts: atom
  gather_facts: yes
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Run update
      apt:
        upgrade: true
        update_cache: yes
      ignore_errors: yes
      become: yes

  post_tasks:
    - name: Run autoremove
      apt:
        autoremove: yes
      become: yes

  tasks:
    - name: Install bettercap
      import_tasks: bettercap.yml

    - name: Setup monitoring
      import_tasks: monitoring.yml

    - name: Setup pihole
      import_tasks: pihole.yml

    - name: Setup portainer
      import_tasks: portainer.yml

    - name: Setup homer
      import_tasks: homer.yml

    - name: Setup jellyfin
      import_tasks: jellyfin.yml

    - name: Setup nextcloud
      import_tasks: nextcloud.yml

    - name: Setup filebrowser
      import_tasks: filebrowser.yml

    - name: Setup nginx
      import_tasks: nginx.yml

    - name: Setup firewall rules
      import_tasks: ufw.yml
