---
- set_fact:
    app: nextcloud
    project_dir: /opt/apps/nextcloud/

- name: Create project directory | {{ app }}
  file:
    path: "{{ project_dir }}"
    state: directory
    owner: "{{ run_user }}"
  become: yes

- name: Synchronize directory | {{ app }}
  synchronize:
    src: apps/nextcloud/
    dest: "{{ project_dir }}"
    delete: false
    recursive: true
    perms: false

- name: Run docker-compose up | {{ app }}
  docker_compose:
    project_src: "{{ project_dir }}"
    build: false
  environment:
    DOCKER_CLIENT_TIMEOUT: 120
    COMPOSE_HTTP_TIMEOUT: 120