version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.5
    container_name: jellyfin
    hostname: jellyfin.atom.lan
    ports:
      - 7359:7359/udp
      - 1900:1900/udp
    expose:
      - 8096
    volumes:
      - jellyfin:/config
      - jellyfin:/cache
      - ./config/network.xml:/config/config/network.xml
      - /media:/media:ro
    env_file:
      - .env
    restart: "unless-stopped"
    networks:
      - front-tier

volumes:
  jellyfin:

networks:
  front-tier:
    external: true