---
version: "3"

volumes:
  jellyfin:

networks:
  front-tier:
    external: true

services:
  jellyfin:
    build: .
    container_name: jellyfin
    hostname: jellyfin.local
    env_file:
      - .env
    ports:
      - 7359:7359/udp
      - 1900:1900/udp
    expose:
      - 8096
    volumes:
      - /media/disk1/movies:/movies:ro
      - /media/disk1/tvshows:/tvshows:ro
      - jellyfin:/config
      - jellyfin:/cache
    restart: "unless-stopped"
    networks:
      - front-tier
