---
version: "3"

volumes:
  config:
  cache:

networks:
  front-tier:
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.5
    container_name: jellyfin
    hostname: jellyfin
    userns_mode: "host"
    env_file:
      - .env
    ports:
      - 7359:7359/udp
      - 1900:1900/udp
    expose:
      - 8096
    volumes:
      - /media/disk1/movies:/movies:ro
      - /media/disk1/tvshows:/tvshows:ro
      - config:/config
      - cache:/cache
      - ./config/network.xml:/config/config/network.xml
      - ./config/system.xml:/config/config/system.xml
    restart: "unless-stopped"
    networks:
      - front-tier
