---
version: "3"

volumes:
  config:
  cache:

networks:
  front-tier:
    external: true

secrets:
  jellyfin_admin_password:
    file: ./secrets/jellyfin_admin_password.txt

services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.7
    container_name: jellyfin
    hostname: jellyfin
    userns_mode: "host"
    env_file:
      - .env
    ports:
      - 7359:7359/udp
      - 1900:1900/udp
    expose:
      - 8096
    volumes:
      - /media/disk1/movies:/movies:ro
      - /media/disk1/tvshows:/tvshows:ro
      - /media/disk1/books:/books:ro
      - /media/disk1/music:/music:ro
      - /media/disk1/photos:/photos:ro
      - /media/disk1/tutorials:/tutorials:ro
      - config:/config
      - cache:/cache
      - ./config/network.xml:/config/config/network.xml
      #- ./config/system.xml:/config/config/system.xml
    secrets:
      - jellyfin_admin_password
    restart: "unless-stopped"
    networks:
      - front-tier
