---
version: "3"

volumes:
  jellyfin:

networks:
  front-tier:
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.5
    container_name: jellyfin
    hostname: jellyfin.local
    env_file:
      - .env
    ports:
      - 7359:7359/udp
      - 1900:1900/udp
    expose:
      - 8096
    volumes:
      - jellyfin:/config
      - jellyfin:/cache
      - ./config/network.xml:/config/config/network.xml
      - /media:/media:ro
    restart: "unless-stopped"
    networks:
      - front-tier
