version: "3.8"

networks:
  network_private:
    external: true

volumes:
  jackett:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /media/disk2/volumes/jackett

services:
  jackett:
    image: linuxserver/jackett:arm64v8-0.20.3917
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_private
        - traefik.http.routers.jackett.tls=true
        - traefik.http.routers.jackett.rule=Host(`${DOMAIN}`) && PathPrefix(`/jackett`)
        - traefik.http.services.jackett.loadbalancer.server.port=9117
    hostname: jackett
    env_file:
      - ./jackett/.env_jackett
      - .vpn_ip
    networks:
      - network_private
    volumes:
      - jackett:/config
      - ./jackett/ServerConfig.json:/config/Jackett/ServerConfig.json
      - ./ip-test.sh:/opt/ip-test.sh
      - /media/disk2/downloads/torrents:/opt/torrents
