version: "3.2"

networks:
  traefik_private:
    external: true
  internal:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 172.16.203.0/24

volumes:
  qbitorrent:
  radarr:

services:
  wireguard:
    image: linuxserver/wireguard:arm64v8-version-v1.0.20210914
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - traefik.enable=false
    hostname: wireguard
    env_file:
      - ./wireguard/.env_wireguard
    networks:
      - internal
      - traefik_private
    cap_add:
      - NET_ADMIN
    volumes:
      - /lib/modules:/lib/modules
      - ./wireguard/wg0.conf:/config/wg0.conf
      - ./wireguard/dante-server/danted.conf:/etc/danted.conf
      - ./wireguard/dante-server/install.sh:/custom-cont-init.d/install.sh:ro
      #- ./wireguard/dante-server/run.sh:/custom-services.d/run.sh:ro
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0

  qbittorrent:
    image: linuxserver/qbittorrent:arm64v8-4.5.2
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.http.routers.qbittorrent.tls=true
        - traefik.http.routers.qbittorrent.rule=PathPrefix(`/qbittorrent`)
        - traefik.http.routers.qbittorrent.middlewares=qbittorrent-stripprefix
        - traefik.http.middlewares.qbittorrent-stripprefix.stripprefix.prefixes=/qbittorrent
        - traefik.http.services.qbittorrent.loadbalancer.server.port=8080
    hostname: qbittorrent
    env_file:
      - ./qbittorrent/.env_qbittorrent
    networks:
      - traefik_private
    volumes:
      - qbitorrent:/config
      - ./qbittorrent/qBittorrent.conf:/config/qBittorrent/qBittorrent.conf
      - /media/disk2/downloads:/downloads

  radarr:
    image: linuxserver/radarr:arm64v8-4.3.2
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.http.routers.radarr.tls=true
        - traefik.http.routers.radarr.rule=PathPrefix(`/radarr`)
        - traefik.http.services.radarr.loadbalancer.server.port=7878
    hostname: radarr
    env_file:
      - ./radarr/.env_radarr
    networks:
      - traefik_private
    volumes:
      - radarr:/config
      - ./radarr/config.xml:/config/config.xml
      - /media/disk2/downloads:/downloads
