---
version: '3'

networks:
  front-tier:
    external: true
  back-tier:
    external: true

volumes:
  prometheus_data:
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:v2.39.0
    container_name: prometheus
    hostname: prometheus
    user: 1050:1750
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=800h' # 30 Days
      - '--web.enable-lifecycle'
      - '--web.external-url=/prometheus/'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - front-tier
      - back-tier
    labels:
      group: "monitoring"

  grafana:
    image: grafana/grafana:9.2.0
    container_name: grafana
    hostname: grafana.lan
    user: 1050:1750
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/
      - ./grafana/images/:/usr/share/grafana/public/img/
    env_file:
      - ./grafana/config.grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    expose:
      - 3000
    #ports:
    #  - 127.0.0.1:3000:3000
    networks:
      - front-tier
      - back-tier
    labels:
      group: "monitoring"

  nodeexporter:
    image: prom/node-exporter:v1.4.0
    container_name: nodeexporter
    hostname: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    depends_on:
      - prometheus
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - back-tier
    labels:
      group: "monitoring"

  cadvisor:
    image: zcube/cadvisor:v0.45.0 # For ARM
    container_name: cadvisor
    hostname: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - prometheus
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - back-tier
    labels:
      group: "monitoring"

  ping:
    image: prom/blackbox-exporter:v0.21.1
    container_name: blackbox_exporter
    hostname: blackbox_exporter
    user: 1050:1750
    tty: true
    stdin_open: true
    expose:
      - 9115
    restart: always
    depends_on:
      - prometheus
    volumes:
      - ./blackbox:/config/
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - front-tier
      - back-tier

  speedtest:
    image: miguelndecarvalho/speedtest-exporter
    container_name: speedtest
    hostname: speedtest
    user: 1050:1750
    expose:
      - 9798
    restart: always
    depends_on:
      - prometheus
    networks:
      - front-tier
      - back-tier
