---
# This deploy-services.yml tasks will be replaced with proper GitOps in future
# https://github.com/veerendra2/raspberrypi-homeserver/issues/54

- name: Create base directory
  ansible.builtin.file:
    path: "{{ services_base_dir_location }}"
    state: directory
    owner: "{{ run_user }}"
  become: yes

# Run pre deploy tasks for services
- include_tasks: pihole.yml
  when: "'pihole' in services"

- name: Create .vpn_ip file for torrent service
  ansible.builtin.copy:
    dest: services/torrent/.vpn_ip
    content: |
      VPN_IP={{ vpn_ip }}
  when: "vpn_ip and 'torrent' in services"

- name: Synchronize services directories
  ansible.posix.synchronize:
    src: "services/"
    dest: "{{ services_base_dir_location }}"
    delete: false
    recursive: true
    perms: false

- name: Create networks
  community.docker.docker_stack:
    state: present
    name: traefik
    compose:
      - "{{ [services_base_dir_location, 'traefik', 'network.yml'] | path_join }}"

- name: Deploy service stacks
  community.docker.docker_stack:
    state: present
    name: "{{ item }}"
    compose:
      - "{{ [services_base_dir_location, item, 'docker-stack.yml'] | path_join }}"
    env:
      DOMAIN: "{{ duckdns_domain }}"
  with_items: "{{ services }}"
