---
- set_fact:
    app: homer
    project_dir: /opt/apps/homer/

- name: Create project directory | {{ app }}
  file:
    path: "{{ project_dir }}"
    state: directory
    owner: "{{ docker_compose_user }}"
  become: yes

- name: Synchronize homer directory | {{ app }}
  synchronize:
    src: apps/homer/
    dest: "{{ project_dir }}"
    delete: false
    recursive: true
    perms: false

- name: Run docker-compose up | {{ app }}
  docker_compose:
    project_src: "{{ project_dir }}"
    build: false
  become_user: "{{ docker_compose_user }}"
