---
- set_fact:
    CUR_USER_HOME: "{{ lookup('env', 'HOME') }}"
    CUR_USER: "{{ ansible_env.USER }}"
    DOCKER_USR_GRP: "_docker"

- name: Install necessary packges
  apt:
    name: "{{ pkgs }}"
    state: latest
    update_cache: yes
  become: true

- name: Install Snap packages
  snap:
    name: "{{ snaps }}"
    classic: yes
  become: true

- name: Install PyPI packages
  pip:
    name: "{{ pypi }}"
    state: present
    executable: "pip3"

- name: Download scripts
  get_url:
    url: "{{ item.value }}"
    dest: "/tmp/{{ item.key }}.sh"
    mode: "0776"
  loop: "{{ lookup('dict', scripts) }}"

- name: Run scripts
  command: "/tmp/{{ item.key }}.sh"
  environment:
    CHANNEL: stable
  become: yes
  loop: "{{ lookup('dict', scripts) }}"

- name: Ensure Docker is started.
  service:
    name: docker
    state: started
    enabled: true

- name: Ensure docker users are added to the docker group
  user:
    name: "{{ CUR_USER }}"
    groups: docker
    append: true
  become: true

- name: Create docker networks
  docker_network:
    name: "{{ item }}"
  with_items:
    - front-tier
    - back-tier

- name: "Create {{ docker_compose_user }} with gid 1750"
  group:
    name: "{{ DOCKER_USR_GRP }}"
    state: present
    gid: 1750

- name: Create {{ docker_compose_user }} with gid 1050
  user:
    name: "{{ docker_compose_user }}"
    groups: "{{ docker_compose_user }},docker"
    shell: /usr/bin/false
    append: yes
    state: present
    uid: 1050
    createhome: no

- name: Make {{ docker_compose_user }} sudoer
  community.general.sudoers:
    name: "{{ docker_compose_user }}"
    state: present
    user: "{{ docker_compose_user }}"
    commands: "ALL"
    sudoers_path: /etc/sudoers.d
    nopassword: true

- name: Build bettercap
  shell: |
    go env -w GO111MODULE=off
    go get -u github.com/bettercap/bettercap
    ls -lah

- name: Install bettercap
  shell: |
    mv {{ CUR_USER_HOME }}/go/bin/bettercap /usr/local/bin/
    rm -rf {{ CUR_USER_HOME }}/go
    bettercap -version
  become: yes
  register: output

- name: Display bettercap version
  debug:
    msg: "{{ output.stdout }}"
  when: output.rc == 0

- name: Install bettercap caplets
  shell: bettercap -eval "caplets.update; ui.update; q"
  when: output.rc == 0
  ignore_errors: true
  become: true
