---
- set_fact:
    app: nginx
    project_dir: /opt/apps/nginx

- name: Create project directory | {{ app }}
  file:
    path: "{{ project_dir }}"
    state: directory
    owner: "{{ run_user }}"
  become: yes

- name: Synchronize directory | {{ app }}
  synchronize:
    src: apps/nginx/
    dest: "{{ project_dir }}"
    delete: false
    recursive: true
    perms: false

- name: Fetching ssl keys status | {{ app }}
  stat:
    path: "{{ item }}"
  register: output
  with_items:
    - "{{ project_dir }}/ssl/server.key"
    - "{{ project_dir }}/ssl/server.pem"

- name: Generating self-signed certificates if required | {{ app }}
  shell: |
    openssl req -x509 -nodes -subj '/CN={{ rpi_hostname }}' -days 365 \
    -newkey rsa:2048 \
    -keyout "{{ project_dir }}/ssl/server.key" \
    -out "{{ project_dir }}/ssl/server.pem"
  when: not output.results[0].stat.exists or not output.results[1].stat.exists
  become: true

# https://github.com/veerendra2/raspberrypi-homeserver/issues/15
- name: Make server.key readable for other users
  file:
    path: "{{ project_dir }}/ssl/server.key"
    mode: '0644'

- name: Run docker-compose up | {{ app }}
  docker_compose:
    project_src: "{{ project_dir }}"
    build: false