---
- name: Create temporary to pigpio build
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: tempdir

- name: Download pigpio
  ansible.builtin.get_url:
    url: https://github.com/joan2937/pigpio/archive/master.zip
    dest: "{{ tempdir.path }}"
    owner: "{{ run_user }}"
    mode: '0440'

- name: Extract pigpio
  ansible.builtin.unarchive:
    src: "{{ tempdir.path }}/pigpio-master.zip"
    dest: "{{ tempdir.path }}"
    remote_src: true

- name: Build and install pigpio
  community.general.make:
    chdir: "{{ tempdir.path }}/pigpio-master"
    target: install
    params:
      NUM_THREADS: 2
  become: true

- name: Set systemd unit parameters for pigpiod
  ansible.builtin.set_fact:
    description: Daemon required to control GPIO pins via pigpio
    exec_start_cmd: /usr/local/bin/pigpiod
    exec_kill_cmd: /bin/systemctl kill pigpiod
    pre_start_cmd: /bin/sleep 0
    require_daemon: network.target
    after_daemon: network.target
    service_type: forking

- name: Create pigpiod systemd unit
  ansible.builtin.template:
    src: templates/systemd_unit.service.j2
    dest: /lib/systemd/system/pigpiod.service
    mode: '0640'

- name: Enable and start pigpiod systemd daemon
  ansible.builtin.systemd:
    name: pigpiod
    enabled: true
    daemon_reload: true
    state: started

- name: Copy fan.py script
  ansible.builtin.copy:
    src: scripts/fan.py
    dest: /usr/local/bin/fan.py
    mode: '0744'

- name: Set systemd unit parameters for fan-py
  ansible.builtin.set_fact:
    description: Daemon required to control fan speed via pigpio
    exec_start_cmd: /usr/bin/python3 /usr/local/bin/fan.py
    exec_kill_cmd: /bin/kill -TERM $MAINPID
    require_daemon: pigpiod.service
    after_daemon: pigpiod.service
    pre_start_cmd: /bin/sleep 5
    service_type: simple

- name: Create fan-py systemd unit file
  ansible.builtin.template:
    src: templates/systemd_unit.service.j2
    dest: /lib/systemd/system/fan-py.service
    mode: '0640'

- name: Enable and start fan-py systemd daemon
  ansible.builtin.systemd:
    name: fan-py
    enabled: true
    daemon_reload: true
    state: started
