---
- set_fact:
    app: pihole
    project_dir: /opt/services/pihole/

# https://github.com/pi-hole/docker-pi-hole#installing-on-ubuntu-or-fedora
- name: Configure systemd-resolved for PiHole
  block:
    - name: Disable stub resolver in systemd-resolved config
      ini_file:
        path: /etc/systemd/resolved.conf
        section: Resolve
        option: DNSStubListener
        value: "no"
        backup: true

    - name: Create backup /etc/resolv.conf
      copy:
        remote_src: yes
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.backup

    - name: Remove /etc/resolv.conf
      file:
        path: /etc/resolv.conf
        state: absent

    - name: Create link /etc/resolv.conf
      file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link

    - name: Restart systemd-resolved
      service:
        name: systemd-resolved
        state: restarted
  become: yes

- name: Create project directory | {{ app }}
  file:
    path: "{{ project_dir }}"
    state: directory
    owner: "{{ run_user }}"
  become: yes

- name: Synchronize project directory | {{ app }}
  synchronize:
    src: services/pihole/
    dest: "{{ project_dir }}"
    delete: false
    recursive: true
    perms: false

- name: Deploy stack | {{ app }}
  docker_compose:
    project_src: "{{ project_dir }}"
    build: false