---
- set_fact:
    app: portainer
    project_dir: /opt/services/portainer/

- name: Create project directory | {{ app }}
  file:
    path: "{{ project_dir }}"
    state: directory
    owner: "{{ run_user }}"
  become: yes

- name: Synchronize directory | {{ app }}
  synchronize:
    src: services/portainer/
    dest: "{{ project_dir }}"
    delete: false
    recursive: true
    perms: false

- name: Deploy stack | {{ app }}
  docker_compose:
    project_src: "{{ project_dir }}"
    build: false