---
- name: Install necessary packages
  apt:
    name: "{{ pkgs }}"
    state: latest
    update_cache: yes
    install_recommends: no
    force_apt_get: yes
  become: true

- name: Install snap packages
  snap:
    name: "{{ snaps }}"
    classic: yes
  become: true

- name: Install pypi packages
  pip:
    name: "{{ pypi }}"
    state: present
    executable: "pip3"

- name: Download scripts
  get_url:
    url: "{{ item.value }}"
    dest: "/tmp/{{ item.key }}.sh"
    mode: "0776"
  loop: "{{ lookup('dict', scripts, wantlist=True) }}"

- name: Run scripts
  command: "/tmp/{{ item.key }}.sh"
  loop: "{{ lookup('dict', scripts, wantlist=True) }}"

- name: Set authorized keys taken from url
  authorized_key:
    user: "{{ run_user }}"
    state: present
    key: "{{ github_username_keys }}"

# POWER OPTIMIZATION
- block:
  - name: Stop and disable hciuart and bluetooth deamon
    systemd:
      name: "{{ item }}"
      state: stopped
      enabled: no
    with_items:
      - bluetooth
      - hciuart

- name: Disable HDMI Output
  shell: /usr/bin/tvservice -o
  become: yes
  when: disable_bluetooth|bool == true

- name: Install pigpio and Pi fan controller
  import_tasks: pigpio.yml

- name: Install and configure docker
  import_tasks: docker.yml

- name: Install bettercap
  import_tasks: bettercap.yml

- name: Reboot Pi after upgrade
  reboot:
    post_reboot_delay: 10
  when: reboot_after_pi_preparation|bool == true
  become: yes

- name: Configure disk mounts in /etc/fstab
  mount:
    path: "{{ item.value }}"
    src: LABEL="{{ item.key }}"
    fstype: ext4
    opts: rw,async
    state: mounted
    boot: no
  loop: "{{ lookup('dict', disk_mount_dirs) }}"
  become: yes

- name: Change mount directories ownership
  file:
    path: "{{ item.value }}"
    owner: "{{ run_user }}"
    group: "{{ run_user }}"
    mode: "0644"
  loop: "{{ lookup('dict', disk_mount_dirs) }}"
  become: yes
