---
- set_fact:
    external_iface_list:
      - eth0
      - wlan0
    allow_tcp_ports:
      - 80
      - 443
      - 22
      - 53
      - 7359
      - 1900
    allow_udp_ports:
      - 53
      - 67

- block:
  # https://github.com/moby/moby/issues/4737#issuecomment-419705925
  - name: Append custom rules in /etc/ufw/after.rules
    blockinfile:
      dest: /etc/ufw/after.rules
      block: "{{ lookup('template', 'templates/override_ufw_rules.j2' ) }}"
      marker: "#{mark} ANSIBLE MANAGED BLOCK"

  - name: Set DEFAULT_FORWARD_POLICY=DROP in /etc/default/ufw
    lineinfile:
      path: /etc/default/ufw
      regexp: '^DEFAULT_FORWARD_POLICY(.*)$'
      line: 'DEFAULT_FORWARD_POLICY="DROP"'
      backup: yes
      backrefs: yes

  - name: Allow selected tcp ports
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    with_items: "{{ allow_tcp_ports }}"

  - name: Allow selected udp ports
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: udp
    with_items: "{{ allow_udp_ports }}"

  - name: Enable ufw
    ufw:
      state: enabled
  become: yes
