---
- name: Set facts
  ansible.legacy.set_fact:
    external_iface_list:
      - eth0
      - wlan0
    allow_tcp_ports:
      - 80
      - 443
      - 22
      - 53
      - 7359
      - 1900
      - 2377
    allow_udp_ports:
      - 53
      - 67

# https://github.com/moby/moby/issues/4737#issuecomment-419705925
- name: Append custom rules in /etc/ufw/after.rules
  ansible.builtin.blockinfile:
    dest: /etc/ufw/after.rules
    block: "{{ lookup('template', 'templates/override_ufw_rules.j2') }}"
    marker: "#{mark} ANSIBLE MANAGED BLOCK"

- name: Set DEFAULT_FORWARD_POLICY=DROP in /etc/default/ufw
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY(.*)$'
    line: 'DEFAULT_FORWARD_POLICY="DROP"'
    backup: true
    backrefs: true

- name: Set IPV6=no in /etc/default/ufw
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    regexp: '^IPV6=(.*)$'
    line: 'IPV6=no'
    backup: true
    backrefs: true

- name: Allow selected tcp ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ allow_tcp_ports }}"

- name: Allow selected udp ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  with_items: "{{ allow_udp_ports }}"

- name: Enable ufw
  community.general.ufw:
    state: enabled
