[global]
  checkNewVersion = true

[api]
  dashboard = true

[log]
  level = "DEBUG"
  filePath = "/traefik.log"

[entryPoints.http]
  address = ":80"
  [entryPoints.http.http.redirections.entryPoint]
    to = "https"
    scheme = "https"

[entryPoints.https]
  address = ":443"
#  [entryPoints.https.http.tls]
#    certResolver = "main"

[tls.stores.default.defaultCertificate]
  certFile = "/etc/ssl/server.pem"
  keyFile = "/etc/ssl/server.key"

#[tls.certificates]
#  certFile = "/etc/ssl/server.pem"
#  keyFile = "/etc/ssl/server.key"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  swarmMode = true
  watch = true