{
 "title": "CPU",
 "tags": [
  "linux",
  "cpu"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(node_boot_time_seconds, host)"
    }
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,10m,1h,6h,12h" },
   { "name": "step", "label": "step", "query": "30s,1m,5m,10m,1h,6h,12h" },
   {
    "name": "cpu",
    "label": "cpu",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cpu)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{host=\"$host\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{host=\"$host\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{host=\"$host\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(count by (cpu)(node_cpu_seconds_total{host='$host'})))"
    }
   ]
  },
  {
   "title": "Average cpu %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{host=\"$host\", mode='idle'}[$interval])))*100"
    }
   ]
  },
  {
   "title": "Min frequency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(node_cpu_frequency_min_hertz{host='$host'})"
    }
   ]
  },
  {
   "title": "Max frequency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(node_cpu_frequency_max_hertz{host='$host'})"
    }
   ]
  },
  {
   "title": "Average frequency %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (avg(node_cpu_scaling_frequency_hertz{host='$host'})-min(node_cpu_frequency_min_hertz{host='$host'})) / (max(node_cpu_frequency_max_hertz{host='$host'})-min(node_cpu_frequency_min_hertz{host='$host'}))"
    }
   ]
  },
  {
   "title": "Throttles core",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_cpu_core_throttles_total{host='$host'})"
    }
   ]
  },
  {
   "title": "Throttles package",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_cpu_package_throttles_total{host='$host'})"
    }
   ]
  },
  {
   "title": "Throttles history",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_core_throttles_total{host=\"$host\"}[$interval]))",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(irate(node_cpu_package_throttles_total{host=\"$host\"}[$interval]))",
     "legendFormat": "Packages"
    }
   ]
  },
  {
   "title": "Average frequency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_cpu_scaling_frequency_hertz{host='$host'})"
    }
   ]
  },
  {
   "title": "CPU $cpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "cpu",
   "targets": [
    {}
   ]
  },
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{host=\"$host\", mode='user', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{host=\"$host\", mode='system', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{host=\"$host\", mode='nice', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{host=\"$host\", mode='idle', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{host=\"$host\", mode='irq', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{host=\"$host\", mode='softirq', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{host=\"$host\", mode='iowait', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "irate(node_cpu_seconds_total{host=\"$host\", mode='steal', cpu='$cpu'}[$interval])",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "node_cpu_frequency_max_hertz{host='$host', cpu='$cpu'}",
     "legendFormat": "max"
    },
    {
     "expr": "node_cpu_scaling_frequency_hertz {host='$host', cpu='$cpu'}",
     "legendFormat": "current"
    },
    {
     "expr": "node_cpu_frequency_min_hertz{host='$host', cpu='$cpu'}",
     "legendFormat": "min"
    }
   ]
  }
 ]
}