{
 "title": "NordVPN",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "\n<img src=/public/img/index.png>"
   }
  },
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "displayType": "Regular", "expr": "nordvpn_status", "valueHandler": "Number Threshold" }
   ]
  },
  {
   "title": "Server",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "targets": [
    { "expr": "nordvpn_connection_info", "legendFormat": "{{current_server}}" }
   ]
  },
  {
   "title": "VPN Settings",
   "type": "table",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "nordvpn_settings_info" }
   ]
  },
  {
   "title": "Country",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "targets": [
    { "expr": "nordvpn_connection_info", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "City",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 3 },
   "targets": [
    { "expr": "nordvpn_connection_info", "legendFormat": "{{city}}" }
   ]
  },
  {
   "title": "Current Technology",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 3 },
   "targets": [
    { "expr": "nordvpn_connection_info", "legendFormat": "{{current_technology}}" }
   ]
  },
  {
   "title": "Protocol",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 3 },
   "targets": [
    { "expr": "nordvpn_connection_info", "legendFormat": "{{current_protocol}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 3 },
   "targets": [
    { "expr": "nordvpn_connection_info", "legendFormat": "{{uptime}}" }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nordvpn_bytes_sent_total" }
   ]
  },
  {
   "title": "Total Bytes Trasfered",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nordvpn_bytes_received_created" }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(nordvpn_bytes_sent_total[5m]) * 60",
     "legendFormat": "Bytes Sent"
    },
    {
     "expr": "rate(nordvpn_bytes_received_total[5m]) * 60",
     "legendFormat": "Bytes Received"
    }
   ]
  },
  {
   "title": "VPN Connection Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "nordvpn_status",
     "legendFormat": "Status",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}