[global]
  checkNewVersion = true

[api]
  dashboard = true

#[accessLog]

[log]
  level = "DEBUG"


[certificatesResolvers.httpResolver.acme]
  email = "test@example.com"
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.httpResolver.acme.dnsChallenge]
    provider = "duckdns"
    resolvers = ["1.1.1.1:53", "8.8.8.8:53"]

[entryPoints.http]
  address = ":80"
  [entryPoints.http.http.redirections.entryPoint]
    to = "https"
    scheme = "https"

[entryPoints.https]
  address = ":443"
  [entryPoints.https.http.tls]
    certResolver = "httpResolver"
    [[entryPoints.https.http.tls.domains]]
      main = "veerendra.duckdns.org"
      sans = ["*.example.com"]

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  swarmMode = true
  watch = true

#[providers.file]
#  filename = "/etc/traefik/dynamic.toml"
