---
version: '3'

volumes:
  nextcloud:

networks:
  front-tier:
    external: true
  back-tier:
    external: true

services:
  postgres:
    image: arm64v8/postgres:14-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    userns_mode: "host"
    env_file:
      - .env_postgres
    volumes:
      - /media/disk2/postgres:/var/lib/postgresql/data:rw
    networks:
      - back-tier
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  nextcloud:
    image: arm64v8/nextcloud:24.0.6-apache
    container_name: nextcloud
    hostname: nextcloud.local
    restart: always
    env_file:
      - .env_nextcloud
    expose:
      - 80
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - front-tier
      - back-tier
    volumes:
      - nextcloud:/var/www/html
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

secrets:
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.txt
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.txt
  postgres_db:
    file: ./secrets/postgres_db.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_user:
    file: ./secrets/postgres_user.txt