---
version: '3'

volumes:
  redis:

networks:
  front-tier:
    external: true
  back-tier:
    external: true

secrets:
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.txt
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.txt
  postgres_db:
    file: ./secrets/postgres_db.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
  redis_host_password:
    file: ./secrets/redis_host_password.txt

services:
  postgres:
    image: arm64v8/postgres:14-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    userns_mode: "host"
    env_file:
      - .env_postgres
    volumes:
      - /media/disk2/postgres:/var/lib/postgresql/data:rw
    networks:
      - back-tier
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    hostname: redis
    restart: always
    command:  [
    "sh", "-c",
    '
    docker-entrypoint.sh
    --requirepass "$$(cat $$REDIS_PASSWORD_FILE)"
    '
    ]
    env_file:
      - .env_redis
    volumes:
      - redis:/data
    networks:
      - back-tier
    secrets:
      - redis_host_password

  nextcloud:
    image: arm64v8/nextcloud:25.0.1-apache
    container_name: nextcloud
    hostname: nextcloud
    restart: always
    env_file:
      - .env_nextcloud
    expose:
      - 80
    links:
      - postgres
    depends_on:
      - postgres
      - redis
    networks:
      - front-tier
      - back-tier
    volumes:
      - /media/disk2/nextcloud:/var/www/html
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user
      - redis_host_password
