version: "3.8"

networks:
  traefik_public:
    external: true
  traefik_private:
    external: true

volumes:
  traefik:

services:
  proxy:
    image: arm64v8/traefik:v2.10.1
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.api.rule=Host(`veerendra.duckdns.org`) && PathPrefix(`/dashboard`) || Host(`veerendra.duckdns.org`) && PathPrefix(`/api`)"
        - "traefik.http.routers.api.entrypoints=https"
        - "traefik.http.routers.api.tls=true"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.services.dummy.loadbalancer.server.port=9999"
    hostname: traefikv2
    env_file:
      - .env_traefik
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/traefik
    networks:
      - traefik_public
      - traefik_private
