---
version: '3'

networks:
  front-tier:
    external: true

services:
  web:
    image: nginx:alpine
    container_name: nginx
    hostname: atom.lan
    volumes:
      - ./server.conf:/etc/nginx/conf.d/default.conf
      - ./locations/test:/etc/nginx/conf.d/locations
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - front-tier
