---
# https://dust6765.gitbook.io/raspberrypi-home-server/services/traefik-proxy
version: "3.8"

networks:
  network_public:
    external: true
  network_private:
    external: true

secrets:
  duckdns:
    file: /media/disk2/volumes/secrets/duckdns.txt

services:
  traefik:
    image: arm64v8/traefik:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.routers.api.tls=true
        - traefik.http.routers.api.entrypoints=https
        - traefik.http.routers.api.tls.certresolver=httpResolver
        - traefik.http.routers.api.rule=Host(`veeru.duckdns.org`) && PathPrefix(`/dashboard`) || Host(`veeru.duckdns.org`) && PathPrefix(`/api`)
        - traefik.http.routers.api.service=api@internal
        - traefik.http.services.dummy.loadbalancer.server.port=9999
    hostname: traefik
    env_file:
      - .env_traefik
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /media/disk2/volumes/traefik:/opt
      - ./config:/etc/traefik
    networks:
      - network_public
      - network_private
    secrets:
      - duckdns
