version: "3.8"

services:
  networks_scratch:
    image: scratch
    deploy:
      replicas: 0
    networks:
      - public
      - private
      - databases
      - monitoring

networks:
  private:
    driver: overlay
    attachable: true
    internal: true
    ipam:
      config:
        - subnet: 172.16.204.0/24

  public:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 172.16.200.0/24

  monitoring:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 172.16.201.0/24

  databases:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 172.16.202.0/24


