version: '3.2'

networks:
  traefik_public:
    external: true

volumes:
  portainer_data:

secrets:
  portainer_admin_password:
    file: ./secrets/portainer_admin_password.txt

services:
  portainer:
    image: portainer/portainer-ce:linux-arm64-2.17.0-alpine
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_public
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.routers.portainer.rule=PathPrefix(`/portainer`)"
        - "traefik.http.routers.portainer.middlewares=portainer-stripprefix"
        - "traefik.http.middlewares.portainer-stripprefix.stripprefix.prefixes=/portainer"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    hostname: portainer
    env_file:
      - .env_portainer
    command:
      - -H
      - unix:///var/run/docker.sock
      - --admin-password-file=/run/secrets/portainer_admin_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik_public
    secrets:
      - portainer_admin_password

