---
version: '3'

networks:
  front-tier:
    external: true

volumes:
  filebrowser:

services:
  filebrowser:
    image: hurlenko/filebrowser:v2.23.0
    container_name: filebrowser
    hostname: filebrowser
    userns_mode: "host"
    env_file:
      - .env
    expose:
      - 8080
    volumes:
      - /media/disk1:/data/disk1
      - /media/disk2:/data/disk2
      - filebrowser:/config
    restart: unless-stopped
    networks:
      - front-tier
