---
# https://dust6765.gitbook.io/raspberrypi-home-server/services/nextcloud
version: '3.8'

networks:
  network_public:
    external: true
  network_databases:
    external: true

secrets:
  nextcloud_admin_password:
    file: secrets/nextcloud_admin_password.txt
  nextcloud_admin_user:
    file: secrets/nextcloud_admin_user.txt
  databases_postgres_password:
    external: true
  databases_postgres_user:
    external: true
  databases_redis_host_password:
    external: true
  databases_postgres_db:
    external: true

services:
  nextcloud:
    image: arm64v8/nextcloud:27.0.1-apache
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.routers.nextcloud.tls=true
        - traefik.http.routers.nextcloud.rule=Host(`veeru.duckdns.org`) && PathPrefix(`/nextcloud`)
        - traefik.http.routers.nextcloud.middlewares=nextcloud-stripprefix
        - traefik.http.middlewares.nextcloud-stripprefix.stripprefix.prefixes=/nextcloud
        - traefik.http.services.nextcloud.loadbalancer.server.port=80
    hostname: nextcloud
    env_file:
      - .env_nextcloud
    networks:
      - network_public
      - network_databases
    volumes:
      - /media/disk2/volumes/nextcloud:/var/www/html
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - databases_postgres_password
      - databases_postgres_user
      - databases_redis_host_password
      - databases_postgres_db
