version: "3.7"
services:
  postgres:
    image: arm64v8/postgres:14-alpine
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: postgres
    env_file:
      - .env_postgres
    volumes:
      - /media/disk2/postgres:/var/lib/postgresql/data:rw
    networks:
      - internal
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  redis:
    image: redis:7.0.5-alpine
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: redis
    command:  [
    "sh", "-c",
    '
    docker-entrypoint.sh
    --requirepass "$$(cat $$REDIS_PASSWORD_FILE)"
    '
    ]
    env_file:
      - .env_redis
    volumes:
      - redis:/data
    networks:
      - internal
    secrets:
      - redis_host_password

  nextcloud:
    image: arm64v8/nextcloud:25.0.1-apache
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: nextcloud
    env_file:
      - .env_nextcloud
    ports:
      - 80:80
    links:
      - postgres
    depends_on:
      - postgres
      - redis
    networks:
      - internal
      - traefik_public
    volumes:
      - /media/disk2/nextcloud:/var/www/html
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user
      - redis_host_password


networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.12.0/24

secrets:
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.txt
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.txt
  postgres_db:
    file: ./secrets/postgres_db.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
  redis_host_password:
    file: ./secrets/redis_host_password.txt

volumes:
  redis:
