version: "3.7"

networks:
  traefik_public:
    external: true
  databases_internal:
    external: true

secrets:
  nextcloud_admin_password:
    file: secrets/nextcloud_admin_password.txt
  nextcloud_admin_user:
    file: secrets/nextcloud_admin_user.txt
  databases_postgres_password:
    external: true
  databases_postgres_user:
    external: true
  databases_redis_host_password:
    external: true
  databases_postgres_db:
    external: true

services:
  nextcloud:
    image: arm64v8/nextcloud:25.0.3-apache
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.nextcloud.rule=PathPrefix(`/nextcloud`)"
        - "traefik.http.routers.nextcloud.tls=true"
        - "traefik.http.routers.nextcloud.middlewares=nextcloud-stripprefix"
        - "traefik.http.middlewares.nextcloud-stripprefix.stripprefix.prefixes=/nextcloud"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    hostname: nextcloud
    env_file:
      - .env_nextcloud
    networks:
      - databases_internal
      - traefik_public
    volumes:
      - /media/disk2/nextcloud:/var/www/html
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - databases_postgres_password
      - databases_postgres_user
      - databases_redis_host_password
      - databases_postgres_db
