---
version: "3"

networks:
  dhcp-relay-net:
    ipam:
      config:
        - subnet: 172.31.0.0/16
  front-tier:
    external: true

volumes:
  pihole:

services:
  pihole:
    image: pihole/pihole:2022.10
    container_name: pihole
    hostname: pihole.atom.local
    restart: unless-stopped
    #userns_mode: "host"
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - 80
    env_file:
      - .env
    volumes:
      - pihole:/etc
      - /etc/resolv.conf:/etc/resolv.conf:ro
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks:
      backend:
          ipv4_address: '172.31.0.100'
      front-tier: {}

  dhcphelper:
    build: ./dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.31.0.100
    cap_add:
      - NET_ADMIN
