---
version: "3"

networks:
  dhcp-relay-net:
    ipam:
      config:
        - subnet: 192.168.0.0/16
  front-tier:
    external: true

volumes:
  pihole:

services:
  pihole:
    image: pihole/pihole:2022.10
    container_name: pihole
    hostname: pihole
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - 80
    env_file:
      - .env
    volumes:
      # - ./etc-pihole:/etc/pihole
      # - ./etc-dnsmasq.d:/etc/dnsmasq.d
      - pihole:/etc
      - ./dnsmasq.d/99-tmp.conf:/etc/dnsmasq.d/99-tmp.conf
      - /etc/resolv.conf:/etc/resolv.conf:ro
    dns:
      - 127.0.0.1
      - 1.1.1.1
    depends_on:
      - dhcphelper
    networks:
      dhcp-relay-net:
          ipv4_address: '192.168.31.10'
      front-tier: {}

  dhcphelper:
    build: ./dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    userns_mode: "host"
    command: -s 192.168.31.10
    cap_add:
      - NET_ADMIN
