version: "3"

services:
  pihole:
    image: pihole/pihole:2022.10
    container_name: pihole
    hostname: pihole.atom.lan
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - 80
    env_file:
      - .env
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      - '/etc/resolv.conf:/etc/resolv.conf:ro'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks:
      - front-tier

networks:
  front-tier:
    external: true