version: "3.0"

services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.9
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    hostname: jellyfin
    env_file:
      - .env
    volumes:
      # Media directory mounts
      - /media/disk1/movies:/movies:ro
      - /media/disk1/tvshows:/tvshows:ro
      - /media/disk1/books:/books:ro
      - /media/disk1/music:/music:ro
      - /media/disk1/photos:/photos:ro
      - /media/disk1/tutorials:/tutorials:ro
      # Jellyfin related
      - config:/config
      - cache:/cache
      - ./config/network.xml:/config/config/network.xml
      - /etc/localtime:/etc/localtime:ro
    deploy:
      labels:
        # traefik common
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:jellyfin.example.com
        - traefik.port=8096

        # traefikv2
        - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.example.com`)"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
        - "traefik.enable=true"

    networks:
      - traefik_public
    ports:
      - 8096:8096

networks:
  traefik_public:
    external: true