---
# https://dust6765.gitbook.io/raspberrypi-home-server/services/jellyfin
version: '3.8'

networks:
  network_public:
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.10
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.routers.jellyfin.tls=true
        - traefik.http.routers.jellyfin.rule=Host(`${DOMAIN}`) && PathPrefix(`/jellyfin`)
        - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    hostname: jellyfin
    env_file:
      - .env_jellyfin
    ports:
      - target: 7359
        published: 7359
        protocol: udp
        mode: host
      - target: 1900
        published: 1900
        protocol: udp
        mode: host
    volumes:
      - ./config/network.xml:/config/config/network.xml
      - ./config/system.xml:/config/config/system.xml
      - /etc/localtime:/etc/localtime:ro
      - /media/disk2:/disk2:ro
      - /media/disk2/volumes/jellyfin/config:/config
      - /media/disk2/volumes/jellyfin/cache:/cache
    networks:
      - network_public
