version: "3.0"

services:
  jellyfin:
    image: jellyfin/jellyfin
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: jellyfin
    env_file:
      - /var/data/config/jellyfin/jellyfin.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/data/jellyfin:/config
      - /var/data/runtime/jellyfin:/cache
      - /var/data/jellyfin/jellyfin:/config
      - /srv/data/:/data
    deploy:
      labels:
        # traefik common
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        # traefikv1
        - traefik.frontend.rule=Host:jellyfin.example.com
        - traefik.port=8096

        # traefikv2
        - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.example.com`)"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
        - "traefik.enable=true"

    networks:
      - traefik_public
    ports:
      - 8096:8096

networks:
  traefik_public:
    external: true