---
version: "3"

networks:
  front-tier:
    external: true

volumes:
  portainer_data:

services:
  portainer:
    image: portainer/portainer-ce:linux-arm64-2.15.1-alpine
    container_name: portainer
    hostname: portainer
    restart: always
    userns_mode: "host"
    command:
      - -H
      - unix:///var/run/docker.sock
      - --admin-password-file=/run/secrets/portainer_admin_password
    networks:
      - front-tier
    expose:
      - 9443
      - 8000
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    secrets:
      - portainer_admin_password

secrets:
  portainer_admin_password:
    file: ./secrets/portainer_admin_password.txt