version: "3.8"

networks:
  trafik_public:
    external: true

services:
  homer:
    image: b4bz/homer:v23.02.1
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    hostname: homer
    env_file:
      - .env
    volumes:
      - ./assets/:/www/assets
    networks:
      trafik_public:
