---
# https://dust6765.gitbook.io/raspberrypi-home-server/services/homer
version: '3.8'

networks:
  network_public:
    external: true

services:
  homer:
    image: b4bz/homer:v23.05.1
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_public"
        - "traefik.http.routers.homer.rule=Host(`${DOMAIN}`) && PathPrefix(`/`)"
        - "traefik.http.routers.homer.tls=true"
        - "traefik.http.services.homer.loadbalancer.server.port=8080"
    hostname: homer
    env_file:
      - .env_homer
    volumes:
      - ./assets/:/www/assets
    networks:
      - network_public
