version: "3.8"

networks:
  traefik_public:
    external: true

services:
  homer:
    image: b4bz/homer:v23.02.1
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.homer.rule=Path(`/`)"
        - "traefik.http.services.homer.loadbalancer.server.port=8080"
    hostname: homer
    env_file:
      - .env
    volumes:
      - ./assets/:/www/assets
    networks:
      traefik_public:
