global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "docker-host-alpha"

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
#rule_files:
#  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: "nodeexporter"
    #scrape_interval: 5s
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: "cadvisor"
    #scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "prometheus"
    #scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "speedtest-exporter"
    scrape_interval: 1h
    scrape_timeout: 1m
    static_configs:
      - targets: ["speedtest:9798"]

  - job_name: "ping"
    metrics_path: /probe
    params:
      module: [http_2xx] # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
          - pinghosts.yml
    relabel_configs:
      - source_labels: [__address__]
        regex: "(.*);(.*)" # first is the url, thus unique for instance
        target_label: instance
        replacement: $1
      - source_labels: [__address__]
        regex: "(.*);(.*)" # second is humanname to use in charts
        target_label: humanname
        replacement: $2
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        replacement: ping:9115 # The blackbox exporter's real hostname:port.
#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    honor_labels: true
#    static_configs:
#      - targets: ['pushgateway:9091']

#alerting:
#  alertmanagers:
#  - scheme: http
#    static_configs:
#    - targets:
#      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
