---
version: "3.8"

networks:
  network_monitoring:
    external: true
  network_public:
    external: true

secrets:
  htpasswd:
    file: secrets/htpasswd.txt

services:
  rest-server:
    image: restic/rest-server:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.routers.rest-server.tls=true
        - traefik.http.routers.rest-server.rule=Host(`veeru.duckdns.org`) && PathPrefix(`/restic`)
        - traefik.http.services.rest-server.loadbalancer.server.port=8000
    hostname: rest-server
    user: 1000:1003
    env_file:
      - .env_rest-server
    volumes:
      - /media/disk2/backups:/restic:rw
    networks:
      - network_public
      - network_monitoring
    secrets:
      - htpasswd
