version: "3.2"

networks:
  traefik_public:
    external: true
  external:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.203.0/24
  internal:
    driver: overlay
    attachable: true
    internal: true
    ipam:
      config:
        - subnet: 172.16.204.0/24

services:
  wireguard:
    image: linuxserver/wireguard:arm64v8-version-v1.0.20210914
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - "traefik.enable=false"
    hostname: wireguard
    networks:
      - internal
      - external
    volumes:
      - /lib/modules:/lib/modules
      - ./config:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0

  deluge:
    image: linuxserver/deluge:arm64v8-2.1.1
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - "traefik.enable=false"
    hostname: deluge
    networks:
      - internal
    volumes:
      - /lib/modules:/lib/modules
      - ./config:/config

