---
version: "3"

networks:
  front-tier:
    external: true

services:
  homer:
    image: b4bz/homer:v22.07.2
    container_name: homer
    hostname: homer
    env_file:
      - .env
    volumes:
      - ./assets/:/www/assets
    expose:
      - 8080
    restart: unless-stopped
    networks:
      - front-tier


