---
version: "3"
services:
  homer:
    image: b4bz/homer:v22.07.2
    container_name: homer
    hostname: homer
    volumes:
      - ./assets/:/www/assets
    expose:
      - 8080
    restart: unless-stopped
    networks:
      - front-tier

networks:
  front-tier:
    external: true
