version: "3.7"

services:
  filebrowser:
    image: hurlenko/filebrowser:v2.23.0
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: filebrowser
    env_file:
      - .env
    volumes:
      - /media/disk1:/data/disk1
      - /media/disk2:/data/disk2
      - filebrowser:/config
    networks:
      trafik_public:

networks:
  trafik_public:
    external: true

volumes:
  filebrowser:
